# Generated by Django 3.1 on 2020-08-25 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Row_Data', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('Notice', models.TextField()),
                ('Visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('Payment_Fill_Date', models.DateField()),
                ('PRM_ID', models.IntegerField()),
                ('Retailer_Name', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('Rifill_mode', models.CharField(choices=[('AUTOREFILL MORNING', 'AUTOREFILL MORNING'), ('AUTOREFILL AFTERNOON', 'AUTOREFILL AFTERNOON')], default='AUTOREFILL MORNING', max_length=20)),
                ('Payment_Remark', models.CharField(choices=[('Pending', 'Pending'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('UPI', 'UPI'), ('NEFT', 'NEFT')], default='Pending', max_length=10)),
                ('Payment_Date', models.DateField(blank=True, null=True)),
                ('Cheque_No', models.IntegerField(blank=True, null=True)),
                ('Bank_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Distributor_Remark', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Cheque_Bounce', 'Cheque_Bounce'), ('Received', 'Received')], default='Pending', max_length=100, null=True)),
                ('Payment_collected_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Row_Data.fos')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('PRM_ID', models.IntegerField()),
                ('Jio_ID', models.IntegerField(blank=True, null=True)),
                ('Retailer_Name', models.CharField(max_length=100)),
                ('Mobile_No', models.IntegerField()),
                ('Whatsapp_No', models.IntegerField()),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Adharcard_no', models.IntegerField()),
                ('Address', models.TextField()),
                ('FOS_Assign', models.ForeignKey(blank=True, default='Vishwamani', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Row_Data.fos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('PRM_ID', models.IntegerField(blank=True, null=True)),
                ('Retailer_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Product', models.CharField(choices=[('Sim Card', 'Sim Card'), ('jio_Phone', 'Jio Phone'), ('Jio_Balance', 'Jio_Balance'), ('Other', 'Other')], default='Sim Card', max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Description', models.CharField(max_length=200)),
                ('Order_Status', models.CharField(choices=[('Pending', 'Pending'), ('In-Process', 'In-Process'), ('Complete', 'Complete')], default='Pending', max_length=100)),
                ('Distributor_Remark', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
